os:
  openCommand: 'code -rg {{filename}}'
gui:
  showCommandLog: false
customCommands:
  - key: f
    command: git f
    subprocess: true
    loadingText: fixup applying...
    description: '"git f", fixup previous commit'
    context: files
